#!/usr/bin/env python
import rospy
import sys
from player.player import Player

def run_node(player):
    while not rospy.is_shutdown():
        player.run()
        rate.sleep()

if __name__ == '__main__':
    try:
        p = Player(int(sys.argv[1]), is_sim=sys.argv[2])
        rospy.init_node('player', anonymous=True)    
        rate = rospy.Rate(60)
        run_node(p)
    except rospy.ROSInterruptException:
        pass
