#!/usr/bin/env python
import rospy
from player.player import Player
from basic_skills.path_planning.rrt import RRT
from basic_skills.path_planning.planner_plotter import PlannerPlotter

def run_node(player):
    plotter = PlannerPlotter(player.planner)
    while not rospy.is_shutdown():
        player.run()
        plotter.draw()
        rate.sleep()
    plotter.close()

if __name__ == '__main__':
    try:
        p = Player(RRT(step_size=100, num_iter=50), 5)
        rospy.init_node('player', anonymous=True)    
        rate = rospy.Rate(60)
        run_node(p)
    except rospy.ROSInterruptException:
        pass
