#!/usr/bin/env  python

import sys

from path_planning_rqt.plugin_module import PlannerViewer
from rqt_gui.main import Main

plugin = 'path_planning_rqt'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
